package pirma.converter2.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JLabel;

public class MyConverter extends JFrame {
  public static int getSum() {
    int sum = 0;
    {
      int number_a = Integer.parseInt("0110", 2);
      sum = sum + number_a;
    }
    {
      int number_b = 50;
      sum = sum + number_b;
    }
    {
      int number_c = Integer.parseInt("111", 2);
      sum = sum + number_c;
    }
    {
      int number_d = Integer.parseInt("AA", 16);
      sum = sum + number_d;
    }
    return sum;
  }
  public static int getSub() {
    int sub = Integer.parseInt("0110", 2) * 2;

    {
      int number_a_0 = Integer.parseInt("0110", 2);
      sub = sub - number_a_0;
    }
    {
      int number_b_0 = 50;
      sub = sub - number_b_0;
    }
    {
      int number_c_0 = Integer.parseInt("111", 2);
      sub = sub - number_c_0;
    }
    {
      int number_d_0 = Integer.parseInt("AA", 16);
      sub = sub - number_d_0;
    }
    return sub;
  }
  public static int getMultipl() {
    int multip = 1;
    {
      int number_a_1 = Integer.parseInt("0110", 2);
      multip = multip * number_a_1;
    }
    {
      int number_b_1 = 50;
      multip = multip * number_b_1;
    }
    {
      int number_c_1 = Integer.parseInt("111", 2);
      multip = multip * number_c_1;
    }
    {
      int number_d_1 = Integer.parseInt("AA", 16);
      multip = multip * number_d_1;
    }
    return multip;
  }
  public static void calculate(String output, JPanel panel) {
    if (output == "sum") {
      System.out.println("The sum is: " + getSum());
      JLabel label = new JLabel("The sum is: " + getSum());
      panel.add(label);
    } else if (output == "sub") {
      System.out.println("The subtraction is: " + getSub());
      JLabel label = new JLabel("The subtraction is:" + getSub());
      panel.add(label);
    } else if (output == "multip") {
      System.out.println("The multiplication is: " + getMultipl());
      JLabel label = new JLabel("The multiplication is:" + getMultipl());
      panel.add(label);
    }
  }
  public static void main(String[] args) {
    String output;
    JFrame frame = new JFrame("Output");
    JPanel panel = new JPanel();

    System.out.println(Integer.parseInt("0110", 2));
    System.out.println(50);
    System.out.println(Integer.parseInt("111", 2));
    System.out.println(Integer.parseInt("AA", 16));
    output = "sum";
    calculate(output, panel);
    output = "sub";
    calculate(output, panel);
    output = "multip";
    calculate(output, panel);

    frame.add(panel);
    frame.setSize(200, 250);
    frame.show();
  }
}
